import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/Styles/Styles.css'
import MobileButtons from './MobileButtons/MobileButtons'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{position:'relative', height: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'space-between'}} className={inter.className}>
        <div className='main-title'>
          <h1 style={{textAlign:'center'}}>
            hello world
          </h1>
        </div>
        <>
          {children}
        </>
      </body>
    </html>
  )
}